SYNGEN ; ; 4/7/22 9:47am
 DO DOB2^SYNSYLVIA1
 D ^SYNSYLVIA1
 DO ASSOCS^SYNSYLVIA2
 D ^SYNSYLVIA2
 D ^SYNSYLVIA3
 DO CANCEL^SYNSYLVIA3
 D ^SYNSYLVIA4
 D FILE^SYNSYLVIA4
 D TEST^SYNRECBPS
 DO ^SYNSYLVIA5
 D ^SYNSYLVIA6
 D ^SYNSYLVIA7
 D END^SYNSYLVIA7
 quit
