SYNHOSPRUN ; ; 3/15/22 1:08pm
 ; D ^MYSQL99
 D ^SYNAGESEX
 D PC^SYNMYSQLX
 D SURNAMES^SYNMYSQLX
 D FIRSTNAMES^SYNMYSQLX
 D HOSP^SYNORGS
 D HOSPSTAFF^SYNSYLVIA1
 D ^SYNAPP1
 D ^SYNAXIN
 D OBSENC^SYNENC1
 D ENC^SYNENC2
 D LIST^SYNENCOUNTER
 D ETHNIC^SYNSYLVIA1
 D BP^SYNMYSQLX
 D LIST^SYNSYLVIA2
 D LIST^SYNSYLVIA4
 D BPCNT^SYNSYLVIA4
 D ^SYNAPP1
 D LIST^SYNSYLVIA6
 D APPCNT^SYNSYLVIA6
 D LIST^SYNSYLVIA8
 D BUILDLIST^SYNSYLVIA8
QUICK ;
 K ^DSYSTEM("DOBFAST")
 D DOBFAST^SYNRANDOM
 D DOB2^SYNSYLVIA1
 D ^SYNSYLVIA1
 D HOSPASSOCS^SYNSYLVIA2
 D ^SYNSYLVIA2
 D ^SYNSYLVIA4
 D FILE^SYNSYLVIA4
 D TEST^SYNRECBPS
 D ^SYNSYLVIA6
 ; D ^SYNSYLVIA7
 D ^SYNSYLVIA8
 quit
