SYNSYLVIA ; ; 3/10/22 4:18pm
 ;
 write !,"run STT^SYNSYLVIA"
 quit
 
 ; STAT COLLECTION
STT K ^AUDIT
 
 D ^SYNAGESEX
 D ^SYNAXIN
 D PC^SYNMYSQLX
 D ^SYNORGS
 D OBSENC^SYNENC1
 D ENC^SYNENC2
 D LIST^SYNENCOUNTER
 D ETHNIC^SYNSYLVIA1
 D ^SYNRX1
 D ^SYNRX2
 D ^SYNAPP1
 D ^SYNCONTACT1
 
 ; allergies
 D GO^SYNALL1
 D BUILDLIST^SYNSYLVIA3
 D BP^SYNMYSQLX
 D LIST^SYNSYLVIA2
 D LIST^SYNSYLVIA3
 D LIST^SYNSYLVIA4
 D BPCNT^SYNSYLVIA4
 
 ; allergies
 D LIST^SYNSYLVIA5
 D BUILDLIST^SYNSYLVIA5
 D ALLCNT^SYNSYLVIA5
 
 ; appointments
 D LIST^SYNSYLVIA6
 D APPCNT^SYNSYLVIA6
 
 ; SYNTHETIC DATA CREATION
 D SURNAMES^SYNMYSQLX
 D FIRSTNAMES^SYNMYSQLX
 D TORG^SYNSYLVIA1
 D P^SYNSYLVIA1
 D DOB2^SYNSYLVIA1
 ; demographics
 D ^SYNSYLVIA1
 
 ;D X^SYNENCOUNTER
 ; encounters
 D ASSOCS^SYNSYLVIA2
 D ^SYNSYLVIA2
 
 ; medication_statement
 D ^SYNSYLVIA3
 D CANCEL^SYNSYLVIA3
 
 ; blood pressures
 D ^SYNSYLVIA4
 D FILE^SYNSYLVIA4
 D TEST^SYNRECBPS
 
 ; allergies
 D ^SYNSYLVIA5
 
 ; appointments
 D ^SYNSYLVIA6
 
 ; contacts
 D LIST^SYNSYLVIA7
 D TYPEUSE^SYNSYLVIA7
 D ^SYNSYLVIA7
 quit
 
QUICK ;
 K ^AUDIT
 D ^SYNSYLVIA1,ASSOCS^SYNSYLVIA2,^SYNSYLVIA2,^SYNSYLVIA3,CANCEL^SYNSYLVIA3,^SYNSYLVIA4,FILE^SYNSYLVIA4,TEST^SYNRECBPS
 D ^SYNSYLVIA5
 D ^EXPORT
 quit
 
GO ;
 D ^SYNSYLVIA2
 D ^SYNSYLVIA3,CANCEL^SYNSYLVIA3
 D ^SYNSYLVIA4,FILE^SYNSYLVIA4,TEST^SYNRECBPS
 D ^SYNSYLVIA5
 D ^SYNSYLVIA6
 D ^SYNSYLVIA7
 QUIT
 
CLEARDOWN ;
 K ^AUDIT,^A,^ADDRESS,^AX,^AXIN,^B,^BP,^BPAV,^BPOBS,^BPREC
 K ^BPX,^COHORT,^ENC,^ENCCODES,^EOC,^ETHNIC,^GARBLE,^LISTS
 K ^MAX,^MAXBP,^MAXLST,^OBS,^OBSBP,^ORGS
 K ^P,^PATIENT,^PATS,^PERSON,^R,^RX
 K ^RXAGE,^RXAXIN,^RXIDX,^RXLIST
 K ^STATS,^STATS2,^STDBP,^T,^TAV
 K ^TBANDS,^TBANDSP,^TDOB,^TDRUG
 K ^TIDX,^TITLE,^TORG,^ZENC
 K ^ZOBSENC,^ZT,^X
 K ^DONE,^FREQ,^ZCOUNTS,^ZCNT,^MAXSD,^ENCAGE
 K ^XAPP,^APP,^ZAPP
 K ^CONTACT
 K ^ZCNTALL,^XRX,^XCONT,^ZTDOB,^AX2,^ALLERGY,^ALLRGYLST
 K ^COUNTS,^COUNTSB,^RX2,^RXORDER
 K ^CONLIST,^CONTIDX
 K ^TM,^DSYSTEM("DOBFAST")
 quit
